<div class="bottombar">
<table width="100%" border="0">
<tr>
<td width="66%" style="padding-bottom:1px;">
<!-- ticker deactivated 8-Sep-2017 , W13
<iframe src="/ticker.php" height="36px" width="99%" scrolling="no" frameborder="0" style="height:36px;vertical-align:middle;background-color:transparent;" allowtransparency="true"></iframe>-->
</td>
<td width="20%" style="text-align:right;">

	<form action="http://www.google.com" id="cse-search-box">
	  <div>
		<input type="hidden" name="cx" value="partner-pub-0109004644664993:3478413701" />
		<input type="hidden" name="ie" value="UTF-8" />
		<input type="text" name="q" size="30" />
		<input type="submit" name="sa" value="Search" />
	  </div>
	</form>

</td>
</tr>
</table>
</div>
