<div style="float:left; width:250px; margin:5px 0 0 15px;">
<table border="0">
<tr>
<td style="padding:0 7px;vertical-align:middle;color:#fff;font-weight:bold;font-size:12px;">THEMES</td><td style="border:none;"><a onclick="changeStyle('bluelight')" title="Default Theme"><img src="/images/banner/default.png" alt="Default" /></a>
<a onclick="changeStyle('bluedark')" title="Black Blue"><img src="/images/banner/blkbl.png" alt="Black Blue" /></a>
<a onclick="changeStyle('redlight')" title="Red Gray"><img src="/images/banner/gryrd.png" alt="Red Gray" /></a>
<a onclick="changeStyle('reddark')" title="Red Black"><img src="/images/banner/blkrd.png" alt="Red Black" /></a>
<a onclick="changeStyle('charcoal')" title="Charcoal"><img src="/images/banner/charc.png" alt="Charcoal" /></a>
<a onclick="changeStyle('greenlight')" title="Dark Green"><img src="/images/banner/grygr.png" alt="Dark Green" /></a>
<a onclick="changeStyle('olivedrab')" title="Olive Drab"><img src="/images/banner/olive.png" alt="Olive Drab" /></a></td></tr></table>
</div>
<div style="float: right; margin:3px 15px 0 0;">
<table border="0" style="color:#fff;font-weight:bold;font-size:12px;">
<tr>
<td style="vertical-align:middle;padding-right:10px">LINKS</td>
<td style="vertical-align:middle;"><a href="/" title="RuneScape Help" target="_blank"><img src="/favicon.ico" alt="" /> 2007RsHelp.com</a> &middot; <a href="https://runescapecommunity.com" title="RuneScape Community" target="_blank"><img src="/favicon.ico" alt="" /> RSC</a> &middot; <a href="http://2007.runescape.wikia.com/wiki/2007scape_Wiki" rel="nofollow" target="_blank"><img src="images/favicon.ico" alt="" /> RS Wiki</a></td></tr></table>
</div>