<html>
<head>
<title>OSRS RuneScape Help Management Center</title>
<link href="/css/darkblue.css" rel="stylesheet" type="text/css" />
<link rev="made" href="mailto:admin@osrs_help.com" />
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<meta name="description" content="An exclusive RuneScape help website that provides all players with the latest skill guides, dungeon maps, quest guides, and loads more!" />
<meta name="keywords" content="runescape, runescape community, runescape help, osrs_help, jagex, guides, magic, maps, tutorials, monsters, games, multiplayer, MMORPG, hints, shops, quests, magic, dungeon, spoilers, walkthrough, clan" />
<meta name="author" content="MDW and Staff" />
<meta name="copyright" content="RuneScape Help &copy; OSRS RuneScape Help Corporation. 2001 - 2006; All rights reserved." />
<meta name="ROBOTS" content="ALL" />
</head>
<body>
<div class="topbar" style="border-top-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-style: solid;"><img src="images/pixel.gif" style="height: 1px; width: 1px;" alt="" /></div>
<div class="bottombar" style="border-top-style: none; border-bottom-style: solid; border-left-style: solid; border-right-style: solid;"><img src="images/pixel.gif" style="height: 1px; width: 1px;" alt="" /></div>
<div id="mtop"><a href="http://2007rshelp.com" title="OSRS RuneScape Help.net"></a></div>
<div class="bottombar" style="border-top-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-style: solid;"><img src="images/pixel.gif" style="height: 1px; width: 1px;" alt="" /></div>
<div class="topbar" style="border-top-style: none; border-bottom-style: solid; border-left-style: solid; border-right-style: solid;"><img src="images/pixel.gif" style="height: 1px; width: 1px;" alt="" /></div>
<br />
<div class="boxtop">
OSRS RuneScape Help Management Center Offline
</div>
<div class="boxbottom">
<p style="text-align: center;">Currently offline due to massive load at RSC.<!--The OSRS RuneScape Help Management Center is offline due to a possible breach in security.<br /><br />A Security vulnerability has been identified. The Management Center will remain offline until it is fixed.Contact Ben_Goten78, W13, No1 1000 or Myst immediately.--></p>
<!--<p style="text-align: center;">If the OSRS RuneScape Help Management Center was turned off in error, please contact Ben_Goten78 or W13.</p>-->
</div>
</body>
</html>