<div class="boxtop">OSRS RuneScape Help</div>
<div class="boxbottom">
<b>Runescape Help</b> (also known as <b>OSRS RuneScape Help</b>) was created in 2001 to provide Runescape players with tips, tricks, and general help. Our main goal since day one has been to focus on <b>quality and innovation</b>. We're always working hard to give you the best. If you have any suggestions, tips, or comments to offer, drop by <a href="http://forums.2007rshelp.com"><b>Runescape Community</b></a> and post a message.<br /><br />
Thank you for visiting, we wish you success in your <b>Runescape career</b>!<br />
- <b>OSRS RuneScape Help team.</b>
</div>