<div class="topbar">
<div style="float:left; width:250px; margin:7px 0 0 15px;">
<table style="border: 0;">
<tr><td class="theader">THEMES</td>
<td style="border:none;"><a onclick="changeStyle('bluelight')" title="Default Theme"><img src="/images/banner/default.png" alt="Default" /></a>
<a onclick="changeStyle('bluedark')" title="Black Blue"><img src="/images/banner/blkbl.png" alt="Black Blue" /></a>
<a onclick="changeStyle('redlight')" title="Red Gray"><img src="/images/banner/gryrd.png" alt="Red Gray" /></a>
<a onclick="changeStyle('reddark')" title="Red Black"><img src="/images/banner/blkrd.png" alt="Red Black" /></a>
<a onclick="changeStyle('charcoal')" title="Charcoal"><img src="/images/banner/charc.png" alt="Charcoal" /></a>
<a onclick="changeStyle('greenlight')" title="Dark Green"><img src="/images/banner/grygr.png" alt="Dark Green" /></a>
<a onclick="changeStyle('olivedrab')" title="Olive Drab"><img src="/images/banner/olive.png" alt="Olive Drab" /></a></td></tr></table>
</div>
</div>
