<nav class="topbar" aria-label="Theme selector">
    <div class="theme-selector">
        <span class="theader">THEMES</span>
        <div class="theme-options">
            <a onclick="changeStyle('bluelight')" title="Default Theme" aria-label="Default Theme">
                <img src="/images/banner/default.png" alt="Default" />
            </a>
            <a onclick="changeStyle('bluedark')" title="Black Blue" aria-label="Black Blue Theme">
                <img src="/images/banner/blkbl.png" alt="Black Blue" />
            </a>
            <a onclick="changeStyle('redlight')" title="Red Gray" aria-label="Red Gray Theme">
                <img src="/images/banner/gryrd.png" alt="Red Gray" />
            </a>
            <a onclick="changeStyle('reddark')" title="Red Black" aria-label="Red Black Theme">
                <img src="/images/banner/blkrd.png" alt="Red Black" />
            </a>
            <a onclick="changeStyle('charcoal')" title="Charcoal" aria-label="Charcoal Theme">
                <img src="/images/banner/charc.png" alt="Charcoal" />
            </a>
            <a onclick="changeStyle('greenlight')" title="Dark Green" aria-label="Dark Green Theme">
                <img src="/images/banner/grygr.png" alt="Dark Green" />
            </a>
            <a onclick="changeStyle('olivedrab')" title="Olive Drab" aria-label="Olive Drab Theme">
                <img src="/images/banner/olive.png" alt="Olive Drab" />
            </a>
        </div>
    </div>
</nav>
