<!-- AddThis Bookmark Button BEGIN -->
<br />
<p style="text-align:center;"><a href="http://www.addthis.com/bookmark.php" onclick="addthis_url=location.href; addthis_title = document.title; return addthis_click(this);" target="_blank"><img src="http://s9.addthis.com/button0-bm.gif" width="83" height="16" border="0" alt="AddThis Social Bookmark Button" /></a> <script type="text/javascript">var addthis_pub = 'osrs_help';</script><script type="text/javascript" src="http://s9.addthis.com/js/widget.php?v=10"></script></p>
<!-- AddThis Bookmark Button END -->


<!-- OSRS RUNE SCAPE HELP SKY 2 (disabled)
 <br />
<script type="text/javascript">
google_ad_client = "pub-0109004644664993";
google_ad_width = 160;
google_ad_height = 600;
google_ad_format = "160x600_as";
google_ad_type = "text_image";
//2007-11-23: osrs_help-sky2
google_ad_channel = "0967778124";
google_color_border = "B3B8BA";
google_color_bg = "FFCCCB";
google_color_link = "0000FF";
google_color_text = "000000";
google_color_url = "008000";
google_ui_features = "rc:10";
</script>
<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
-->




<!-- NORIGHTCLICK -->
<!--// No Right Click
var message = "COPYRIGHT NOTICE:\n\nRuneScape Help © OSRS RuneScape Help Corporation. 2001 - 2007; All rights reserved.\n\nAll content is for use on OSRS RuneScape Help.net ONLY!\n\nRunescape is registered trademark of Jagex Ltd.";

function clickIE4()
{
 if (event.button == 2)
  {
   //alert(message);
   //return false;
  }
}

function clickNS4(e)
{
 if (document.layers || document.getElementById && ! document.all)
  {
   if (e.which == 2 || e.which == 3)
    {
     //alert(message);
     //return false;
    }
  }
}

if (document.layers)
{
 document.captureEvents(Event.MOUSEDOWN);
 document.onmousedown = clickNS4;
}
else if (document.all && ! document.getElementById)
{
 document.onmousedown = clickIE4;
}

//document.oncontextmenu = new Function("alert(message); return false;")
-->
<!-- END NORIGHTCLICK -->

<!-- TOP ADS -->

	<!--<script type="text/javascript">
	google_ad_client = "pub-0109004644664993";
	google_ad_width = 468;
	google_ad_height = 60;
	google_ad_format = "468x60_as";
	google_ad_type = "text_image";
	//2007-06-06: 2007rshelp.com
	google_ad_channel = "8083889722";
	google_color_border = ["FFFFFF","336699","000000","6699CC"];
	google_color_bg = ["FFFFFF","FFFFFF","F0F0F0","003366"];
	google_color_link = ["0000FF","0000FF","0000FF","FFFFFF"];
	google_color_text = ["000000","000000","000000","AECCEB"];
	google_color_url = ["008000","008000","008000","AECCEB"];
	</script>
	<script type="text/javascript"
	  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
	</script>

	<br />
	<span style="text-align: center; color: white; font-size: 8pt;">Advertisement</span>-->

<!-- END TOP ADS -->

<!-- SIDE ADS -->

	<!--
	<font size="2" color="white">Advertisement</font><br />
	<br />
	<a href="http://www.runescapeguide.com/" target="_blank" rel="nofollow"><img src="http://2007rshelp.com/images/rsg120x600.gif" border="0" alt="Advertisement" /></a>
	-->

	<!--
	<script type="text/javascript">
	google_ad_client = "pub-0109004644664993";
	google_alternate_color = "FFFFFF";
	google_ad_width = 120;
	google_ad_height = 600;
	google_ad_format = "120x600_as";
	google_ad_type = "text_image";
	//2007-07-03: 2007rshelp.com
	google_ad_channel = "8083889722";
	google_ui_features = "rc:6";
	</script>
	<script type="text/javascript"
	  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
	</script>
	-->

<!-- END SIDE ADS -->

<!-- SIDE STUFF -->

	<!--<form action="/search/index.php" method="post" class="boxbottom" style="padding: 1px; border-top-style: solid; margin-bottom: 12px;"><table style="width: 100%;"><tr> 
	<td><input type="text" maxlength="255" name="s" style="width: 98%;" value="Search OSRS RuneScape Help" onfocus="this.value='';" /></td> 
	<td width="60"><input type="button" onclick="javascript:if(this.form.s.value=='Search OSRS RuneScape Help'){location='/search/index.php';}else{this.form.submit();}" value="Search" /></td> 
	</tr></table></form>-->
	
	<!--<li>&nbsp;&nbsp;&nbsp;- <a href="/faq.php" title="OSRS RuneScape Help Frequently Asked Questions">OSRS RuneScape Help F.A.Q.</a></li>-->

<!-- END SIDE STUFF -->

<!-- FOOTER -->

	<!-- - [ Server Load: <span style="color: #FFA500">[#LOAD#]</span> ]-->

<!-- END FOOTER -->