<!--The copyright notice is overkill imho - W13 (Dec 3, 2013)
<p style="text-align:center; font-weight:bold; margin-bottom:2em;">
<span style="text-decoration:underline;">Content Copyright Notice</span>:<br />
All Content is Copyright &copy; 2007RsHelp.com, 2001 - 2019. 
<br /><br />All guides, images and information submitted to Zybez become property of Zybez. Use on any other website is PROHIBITED! Content may only be used on other websites with permission from Zybez AND the author.</p>
-->

<p style="text-align:center; margin-bottom:2em;font-weight:bold;font-size:1.5em;">
<img src="/img/news/handsandattack.png" />
Stuck on something? Want some more tips? <a href="https://runescapecommunity.com">Ask on our forums.</a>
<img src="/img/news/gobbow.png" />
</p>
