<div class="navigation">
<h3>OSRS RuneScape Help</h3>
<ul>
<li><a href="/" title="2007 RuneScape Help"><img alt="" src="/images/banner/house.png" />OSRS RuneScape Help</a></li>
<li><a href="https://runescapecommunity.com/" title="Runescape Community discussion forums"><img alt="" src="/images/banner/user_comment.png" />RuneScape Community Forums</a></li>
</ul>
<h3>Guides</h3>
<ul>
<li><a href="/skills.php" title="Runescape Skill Guides for skills such as Farming, Crafting, Summoning and more"><img alt="" src="/images/banner/chart_bar.png" />Skill Guides</a></li>
<li><a href="/quests.php" title="Runescape Quest Guides and detailed tips on how to complete them"><img alt="" src="/images/banner/quest.png" />Quest Guides</a></li>
<li><a href="/cities.php" title="Runescape City Guides for major towns and areas"><img alt="" src="/images/banner/building.png" />City Guides</a></li>
<li><a href="/guilds.php" title="Runescape Guild Guides for guilds such as Cooking Guild, Heros Guild and Champions Guild"><img alt="" src="/images/banner/shield.png" />Guild Guides</a></li>
<li><a href="/minigames.php" title="Runescape Mini Game Guides and Tips"><img alt="" src="/images/banner/minigame.png" />Mini Game Guides</a></li>
<li><a href="/misc.php?id=57" title="Runescape Treasure Trail Help"><img alt="" src="/images/banner/treasure.png" />Treasure Trail Help</a></li>
<li><a href="/misc.php" title="Lots of interesting Runescape guides and tips"><img alt="" src="/images/banner/book_open.png" />Miscellaneous Guides</a></li>
<li><a href="/dungeonmaps.php" title="Runescape Dungeon Maps"><img alt="" src="/images/banner/map2.png" />Dungeon Maps</a></li>
<li><a href="/miningmaps.php" title="Runescape Mining Maps"><img alt="" src="/images/banner/hammer.png" />Mining Maps</a></li>
</ul>
<h3>Databases</h3>
<ul>
<!--<li><a href="http://forums.2007rshelp.com/runescape-2007-prices" title="Runescape Market Prices of items Database"><img alt="" src="/images/banner/coins.png" />Prices Database</a></li>
-->
<li><a href="/items.php" title="Runescape Item Database"><img alt="" src="/images/banner/wand.png" />Items Database</a></li>
<li><a href="/monsters.php" title="Runescape Monster Database"><img alt="" src="/images/banner/bug.png" />Monsters Database</a></li>
<li><a href="/shops.php" title="Runescape Shop Database"><img alt="" src="/images/banner/basket.png" />Shops Database</a></li>
<li><a href="/tomes.php" title="Runescape Tome or Book Database"><img alt="" src="/images/banner/book.png" />Tome/Books Database</a></li>
</ul>
<h3>Tools</h3>
<ul>
<!-- broken in PHP7 <li><a href="/compare.php" title="Runescape Item Comparison"><img alt="" src="/images/banner/compare.png" />Item Comparison</a></li>-->
<li><a href="/calcs.php" title="Runescape Skill Calculators"><img alt="" src="/images/banner/calculator.png" />Skill Calculators</a></li>
<li><a href="/locator.php" title="Runescape Co-ordinate Locator"><img alt="" src="/images/banner/map.png" />Coordinate Locator</a></li>
</ul>
<h3>Community</h3>
<ul>
<li><a href="https://runescapecommunity.com" title="Runescape Community forums"><img alt="" src="/images/banner/user_comment.png" />Runescape Community Forums</a></li>
<!--<li><a href="https://discordapp.com/invite/j3ffhGk" title="OSRS RuneScape Help Discord"><img alt="" src="/images/banner/discord.png" />Discord</a></li>-->
<li><a href="/misc.php?id=75" title="OSRS RuneScape Help Runescape Clan Chat"><img alt="" src="/images/banner/zchat.png" />Zchat Clan Chat</a></li>
</ul>
</div>

<?php

if($_SERVER['PHP_SELF']!="/index.php"){

?>
<div class="navigation">
<!-- Google vertical banner below nav -->
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- SideBar -->
<ins class="adsbygoogle"
     style="display:inline-block;width:160px;height:600px"
     data-ad-client="ca-pub-0109004644664993"
     data-ad-slot="2647397929"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>

</div>
<?php
}
?>
