<!-- Advert Top: Start -->
<div style="position: absolute; direction: rtl; right: 1%; top: 3%; width:468; height:70;">
<a href="http://www.gamergifts.net/portal/cmps_index.php" rel="nofollow" target="_blank"><img src="http://gamergifts.net/runescapebanner.jpg" border="0" alt="Advertisement" /></a><!-- expiry: dec 17 2007-->
</div>
<!-- Advert Top: End -->

<!-- Advert Side: Start -->
<div style="text-align:center">
<script type="text/javascript"><!--
google_ad_client = "pub-0109004644664993";
google_ad_width = 160;
google_ad_height = 600;
google_ad_format = "160x600_as";
google_ad_type = "text_image";
//2007-11-18: 2007rshelp.com
google_ad_channel = "8083889722";
google_color_border = "B3B8BA";
google_color_bg = "CAF99B";
google_color_link = "0000FF";
google_color_text = "000000";
google_color_url = "008000";
google_ui_features = "rc:10";
//-->
</script>
<script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
<br />
<script type="text/javascript"><!--
google_ad_client = "pub-0109004644664993";
google_ad_width = 160;
google_ad_height = 600;
google_ad_format = "160x600_as";
google_ad_type = "text_image";
//2007-11-23: osrs_help-sky2
google_ad_channel = "0967778124";
google_color_border = "B3B8BA";
google_color_bg = "CAF99B";
google_color_link = "0000FF";
google_color_text = "000000";
google_color_url = "008000";
google_ui_features = "rc:10";
//-->
</script>
<script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>

</div>
<!-- Advert Side: End -->