<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<title>[#SITE_NAME#]</title>
<script src="/editor/extras/popups.js" type="text/javascript"></script>
<link href="[#CSS#].css" rel="stylesheet" type="text/css" id="ourstylesheet" />
<link href="/css/global.css" rel="stylesheet" type="text/css" />
<link href="/css/editor.css" rel="stylesheet" type="text/css" />
<style type="text/css">#wrapper {min-width:590px !important} </style>
</head>
<body>
<div id="wrapper">
[#CONTENT#]
</div>
</body>
</html>