<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<title>[#SITE_NAME#] ([#QUERIES#])</title>
<script src="/editor/extras/popups.js" type="text/javascript"></script>
<link href="[#CSS#]" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="wrapper">
[#CONTENT#]
</div>
</body>
</html>