<div class="boxtop">Runescape Quest Guides</div><div class="boxbottom" style="padding-left: 24px; padding-top: 6px; padding-right: 24px;">
<a name="top"></a>
<div style="text-align: left; margin: 1px;">
<strong><span style="font-size: large;">&raquo; Runescape Quest Guides</span></strong>
</div>
<hr class="main" noshade="noshade" />
<br />
<table style="border-left: 1px solid #000000; border-top: 1px solid #000000; width: 100%;" cellpadding="1" cellspacing="0">
 <tr class="boxtop">
  <th style="border-bottom: 1px solid #000000; border-right: 1px solid #000000">Name:</th>
  <th style="border-bottom: 1px solid #000000; border-right: 1px solid #000000">Type:</th>
  <th style="border-bottom: 1px solid #000000; border-right: 1px solid #000000">Author:</th>
 </tr>